### ISSUE TITLE
background img da xatolik bor

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#1]
hozirgi holat:
![image](https://user-images.githubusercontent.com/102718840/166111180-b559b56a-dccb-4c7a-aa56-a66d60afd80c.png)

kutilgan natija:
![image](https://user-images.githubusercontent.com/102718840/166111231-637ea6c4-c84e-4fec-9a9b-5f52a18b85d3.png)

ekrani uzoq yaqin qilganda chap tomondagi background img rasmi kotta kichik bo'lmayapti

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134172-d9cbc152-f987-49b6-bfcb-101a4c09fc9b.png)
