### ISSUE TITLE
html tilda

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#2]
hozirgi xolat:
![image](https://user-images.githubusercontent.com/102718840/166111347-a6399954-bb6e-49e7-b978-e1ad08c0f723.png)

kutilgan natija:
![image](https://user-images.githubusercontent.com/102718840/166111377-40e10cb7-c5da-41b2-974f-9d46d7531bba.png)

agar tuzilyakan sayt o'zbekcha bo'lsa languageni uz qilib qo'yish kerak. Qo'shimcha titleda ham tuzilyakan maket yokiz sayt o'zbekcha bo'lsa uni o'zbekcha nom bilan berilsa yaxshi

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134186-b5d152bf-3965-4c54-ac00-e725cb9a659f.png)
