### ISSUE TITLE
Mainda xatolik

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#3]
hozirgi xolat:
![image](https://user-images.githubusercontent.com/102718840/166111519-7beb0596-08bb-4363-bcb5-798ead324a1b.png)

kutilgan natija:
![image](https://user-images.githubusercontent.com/102718840/166111550-d7cc27f7-4baa-4a5f-8c16-d7b0afaf0b45.png)

chap tomondagi background img rasmini chap tomonida joy tashlanmagan ekranga yopishib qolgan. ustozdi maketlarida joy tashlab ketilgan

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134334-9e615957-8fc9-4877-bbc6-455491fef913.png)

Men maket tuzilgan videolarni ko'rishdan oldin maketni o'zim tuzip ko'rip, keyin videolarni ko'ryapman )
