### ISSUE TITLE
Mainda xatolik o'ng tarafda

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#4]
hozirgi xolat:
![image](https://user-images.githubusercontent.com/102718840/166111689-91f0e711-9189-4530-a464-4ef2a51db818.png)

kutilgan natija:
![image](https://user-images.githubusercontent.com/102718840/166111722-e10b656d-97c7-4715-a6f8-4c1d493cfd37.png)

sizda o'ng tomondagi boxga background color berilmagan. Agar brauzerni tungi rejimidan foydalanadigan foydalanuvchi bundan foydalansa yozuvlar ko'rinme qolishi mumkin.

Agar o'ng tomondagi boxga background-color oq berilsa har qanday xolataham sayt sifati buzilmedi

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134393-89151892-b099-4c7a-a66e-7e0e408562b1.png)
