### ISSUE TITLE
google fonts

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#5]
sizdagi holat:
![image](https://user-images.githubusercontent.com/102718840/166112274-a29a7c31-4a75-418b-8aed-841ddfcf05ea.png)

maketdagi holat:
![image](https://user-images.githubusercontent.com/102718840/166112291-2ac2781b-26e7-4289-979d-b4842df9cd81.png)

sizda shriftlar to'g'ri ulangan lekin manimcha kerakli shriftlarni to'g'ri funksiyalari tanlanmagan.

Masalan Roboto-Condensedni ulagansiz lekin uni 400li va 700 variantlarini tanlamagansiz

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134423-26089258-8895-45ac-8ba7-7ae1d6d8e6e1.png)
