### ISSUE TITLE
maini pastidagi buttonda xato

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#6]
sizdagi holat:
![image](https://user-images.githubusercontent.com/102718840/166112434-64b0de5b-1575-45f4-96ae-e44c243d077f.png)

maketdagi xolat:
![image](https://user-images.githubusercontent.com/102718840/166112477-6d78d5b8-4040-4786-8852-ebb5b4b046e9.png)

siz yana yuklashni linkda bergansiz uni buttinda berish kerak

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134533-f2f4b13f-be80-4535-8bf7-3ecb0bfeb357.png)
