### ISSUE TITLE
buttonda xatolik

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#7]
sizdagi xolat:
![image](https://user-images.githubusercontent.com/102718840/166112576-55acd517-66a1-47c4-9379-9f3a0d76baa7.png)

kutilgan natiaj:
![image](https://user-images.githubusercontent.com/102718840/166112593-4cc728f6-12a8-43b3-8df1-d1eb9942fe5a.png)

sizda buttoni width cho'zilib ketyapti

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134600-ed50ad94-5aec-44ab-b253-4116957c0788.png)
