### ISSUE TITLE
mainda img da kichik xatolik bor

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#8]
sizdagi holat:
![image](https://user-images.githubusercontent.com/102718840/166112686-3b96622f-9d22-47d7-8279-4581ab4fe627.png)

tavsiya qilinadigan xolat:
![image](https://user-images.githubusercontent.com/102718840/166112709-a537ce11-35bc-43cf-a062-7c4b46cf1c9c.png)

sizda imglarni alti hammasi bir xil yana u berilgan nom maketdagi rasmga yaqin ham emas. Imglardagi alt ko'zi ojizlar bu saytdan foydalanganda altdagi nom ulargan qanday rasm qo'yilganini bilib olishga yordam beradi. iloji boricha rasmga moslab yozish kerak altini ham

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/166134695-8d8e8e5a-b181-4525-b524-7b0a60095fd0.png)
