### ISSUE TITLE
maindagi psevdoelementlarda xatolik bor

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Articles#9]
sizdagi holat:
![image](https://user-images.githubusercontent.com/102718840/166112961-924a071e-dd53-493a-8f8e-e946c6457f30.png)

maketdagi xolat:
![image](https://user-images.githubusercontent.com/102718840/166112989-fdbc5f13-45d1-4060-9f9c-e5c87b000729.png)

**Comment by Sardor0795** [comment]
Maketdagiday o'lcham yozilsa ko'z iconi kichkina ko'rinip qolyapti:
![image](https://user-images.githubusercontent.com/87645525/166134289-a14cab40-413a-44e4-8fbd-0c103aaf7294.png)


Shuning uchun ko'rinishini biroz to'g'irladim:
![image](https://user-images.githubusercontent.com/87645525/166134254-62d95523-6db2-4506-87c0-392a8c628088.png)

Menimcha shu ko'rinishi yaxshi!!!
